/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cresb.proyectoio.fronted;

import com.cresb.proyectoio.fronted.entidades.Nodo;
import com.cresb.proyectoio.fronted.entidades.ProcesadoActividades;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benjamin
 */
public class Inicio extends javax.swing.JFrame {

    private int id = 0;
    private ArrayList<Nodo> nodos;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        this.setTitle("Ruta Critica CPM");
        nodos = new ArrayList<Nodo>();
        initComponents();
        this.cargaAutomatica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputDuracion = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Ingrese las actividades de su proyecto");

        jLabel2.setText("CALCULO DE RUTA CRITICA CPM");

        jLabel3.setText("Nombre:");

        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Duracion:");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Duracion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Limpiar Datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Asignar Presedencia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Resultado Final");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(inputDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(149, 149, 149)
                                .addComponent(jButton3)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(inputDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.inputName.getText().isBlank() || this.inputDuracion.getText().isBlank()) {
            System.out.println("Datos en Blanco");
        } else {
            System.out.println("Hay datos");
            Nodo nodo = new Nodo(this.inputName.getText(), id, Integer.parseInt(this.inputDuracion.getText()));
            System.out.println(nodo.toString());
            this.agregarTabla(nodo);
            this.id++;
            this.eliminarEntrada();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.eliminarEntrada();
        this.reiniciarContador();
        this.deleteAllRows((DefaultTableModel) jTable1.getModel());
        nodos = null;
        nodos = new ArrayList<Nodo>();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(nodos.isEmpty()){
            System.out.println("No hay datos a procesar");
        }else{
            Asignacion asig = new Asignacion(this, true, nodos);
            asig.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ProcesadoActividades procesado = new ProcesadoActividades();
        
        procesado.calcularTiemposInicio(nodos);
        procesado.calcularTiemposFin(nodos);
        System.out.println("***********************************************");
        for(Nodo actividad:this.nodos){
            System.out.println(actividad.toString());
        }
        System.out.println("***********************************************");
        
        if(nodos.isEmpty()){
            System.out.println("No hay datos a procesar");
        }else{
            PresentacionInfo info = new PresentacionInfo(this, true, nodos);
            info.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField inputDuracion;
    private javax.swing.JTextField inputName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void agregarTabla(Nodo nodo) {
        //Sección 1 
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        //Sección 2
        Object[] fila = new Object[3];
        //Sección 3
        fila[0] = nodo.getId();
        fila[1] = nodo.getNombre();
        fila[2] = nodo.getDuracion();
        //Sección 4
        modelo.addRow(fila);
        //Sección 5
        jTable1.setModel(modelo);
        this.agregarDato(nodo);
    }

    private void eliminarEntrada() {
        this.inputDuracion.setText("");
        this.inputName.setText("");
    }

    private void reiniciarContador() {
        this.id = 0;
    }

    private void deleteAllRows(final DefaultTableModel model) {
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }

    private void agregarDato(Nodo nodo) {
        this.nodos.add(nodo);
    }

    private void cargaAutomatica() {
        Nodo nodo1 = new Nodo("Análisis de Infraestructura", 0, 3);
        Nodo nodo2 = new Nodo("Diseños y planos construccion e instalacion", 1, 6);
        Nodo nodo3 = new Nodo("Análisis de Impacto Ambiental", 2, 4);
        Nodo nodo4 = new Nodo("Cotización de Maquinaria", 3, 2);
        Nodo nodo5 = new Nodo("Adquisición de Maquinaria", 4, 7);
        Nodo nodo6 = new Nodo("Preparación de Infraestructura", 5, 6);
        Nodo nodo7 = new Nodo("Instalación de Maquinaria", 6, 3);
        Nodo nodo8 = new Nodo("Alimentación y refrigeración de maquinaria", 7, 5);
        Nodo nodo9 = new Nodo("Implementación de sala de comandos", 8, 4);
        Nodo nodo10 = new Nodo("Instalación de PLC´s y configuración inicial", 9, 1);
        Nodo nodo11 = new Nodo("Programación del sistema general para el control de PLC´s", 10, 10);
        Nodo nodo12 = new Nodo("Testeo y ajustes del sistema en general", 11, 3);
        Nodo nodo13 = new Nodo("Contratación de ingenieros", 12, 4);
        Nodo nodo14 = new Nodo("Capacitación de los ingenieros  para el manejo del sistema", 13, 3);
        
        this.agregarTabla(nodo1);
        this.agregarTabla(nodo2);
        this.agregarTabla(nodo3);
        this.agregarTabla(nodo4);
        this.agregarTabla(nodo5);
        this.agregarTabla(nodo6);
        this.agregarTabla(nodo7);
        this.agregarTabla(nodo8);
        this.agregarTabla(nodo9);
        this.agregarTabla(nodo10);
        this.agregarTabla(nodo11);
        this.agregarTabla(nodo12);
        this.agregarTabla(nodo13);
        this.agregarTabla(nodo14);
        
        nodo2.getPresendecia().add(nodo1);
        nodo1.getSiguiente().add(nodo2);
        
        nodo4.getPresendecia().add(nodo3);
        nodo3.getSiguiente().add(nodo4);
        
        nodo5.getPresendecia().add(nodo4);
        nodo6.getPresendecia().add(nodo4);
        nodo4.getSiguiente().add(nodo5);
        nodo4.getSiguiente().add(nodo6);
        
        nodo6.getPresendecia().add(nodo2);
        nodo2.getSiguiente().add(nodo6);
        
        nodo7.getPresendecia().add(nodo5);
        nodo7.getPresendecia().add(nodo6);
        nodo5.getSiguiente().add(nodo7);
        nodo6.getSiguiente().add(nodo7);
        
        
        nodo8.getPresendecia().add(nodo7);
        nodo7.getSiguiente().add(nodo8);
        
        nodo9.getPresendecia().add(nodo6);
        nodo9.getPresendecia().add(nodo7);
        nodo6.getSiguiente().add(nodo9);
        nodo7.getSiguiente().add(nodo9);
        
        nodo10.getPresendecia().add(nodo8);
        nodo8.getSiguiente().add(nodo10);
        
        nodo11.getPresendecia().add(nodo10);
        nodo10.getSiguiente().add(nodo11);
        
        nodo12.getPresendecia().add(nodo9);
        nodo12.getPresendecia().add(nodo11);
        nodo9.getSiguiente().add(nodo12);
        nodo11.getSiguiente().add(nodo12);
        
        nodo13.getPresendecia().add(nodo12);
        nodo12.getSiguiente().add(nodo13);
        
        nodo14.getPresendecia().add(nodo13);
        nodo13.getSiguiente().add(nodo14);
        
    }

}
