/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cresb.proyectoio.fronted;

import com.cresb.proyectoio.fronted.entidades.Nodo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benjamin
 */
public class PresentacionInfo extends javax.swing.JDialog {

    private ArrayList<Nodo> actividades;

    /**
     * Creates new form PresentacionInfo
     */
    public PresentacionInfo(java.awt.Frame parent, boolean modal, ArrayList<Nodo> actividades) {
        super(parent, modal);
        initComponents();
        this.actividades = actividades;
        this.cargarActividadesTotal();
        this.cargarActividadesCriticas();
        this.mostrarDuracion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        OutTiempoduracion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RESULTADOS DEL ANALISIS DEL PROYECTO");

        jLabel1.setText("Duracion del Proyecto:");

        OutTiempoduracion.setEditable(false);

        jLabel2.setText("unidades de tiempo");

        jLabel3.setText("Actividades Criticas:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre Actividad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Resumen de Actividades");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Duracion", "Inicio Temprado", "Inicio Tardio", "Fin Cercano", "Fin Tardio", "Holgura"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OutTiempoduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(OutTiempoduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OutTiempoduracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void cargarActividadesTotal() {
        //Sección 1 
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        for (Nodo actividade : actividades) {

            //Sección 2
            Object[] fila = new Object[8];
            //Sección 3
            fila[0] = actividade.getId();
            fila[1] = actividade.getNombre();
            fila[2] = actividade.getDuracion();
            fila[3] = actividade.getIniTemprano();
            fila[4] = actividade.getIniTardio();
            fila[5] = actividade.getFinTemprano();
            fila[6] = actividade.getFinTardio();
            fila[7] = actividade.getHolgura();
            //Sección 4
            modelo.addRow(fila);
            //Sección 5
            //Sección 5
            jTable2.setModel(modelo);

        }
    }

    private void cargarActividadesCriticas() {
        //Sección 1 
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        for (Nodo actividade : actividades) {
            if (actividade.getHolgura() == 0) {
                //Sección 2
                Object[] fila = new Object[2];
                //Sección 3
                fila[0] = actividade.getId();
                fila[1] = actividade.getNombre();
                //Sección 4
                modelo.addRow(fila);
                //Sección 5
                //Sección 5
                jTable1.setModel(modelo);
            }
        }
    }

    private void mostrarDuracion() {
        double tmp = -1;
        for (Nodo actividade : actividades) {
            if(tmp == -1){
                tmp = actividade.getFinTemprano();
            }else{
                if(actividade.getFinTemprano()>tmp){
                    tmp = actividade.getFinTemprano();
                }
            }
        }
        this.OutTiempoduracion.setText(String.valueOf(tmp));
    }
}
